### ISSUE TITLE
some suggested pre-Pentium II tests

### ISSUE THREAD

**Issue by peterferrie** [barotto/test386.asm#1]
overflow flag for AAA, AAS, DAA, DAS (set according to result); 0bd4930

overflow flag test for BT (it's a ~~ROL~~ RCR with CF=0, at least on a 386); df41731

flags test for RCL and RCR with byte and count=9 or word and count=17 (rotate should still happen and set flags); 3b22df3

aux flag test for SHL and SHR (always set if count>0); 866b145

flags test for SHL with byte and count=16/24/32 (behaves like count=8) or word and count=32 (behaves like count=16); 866b145

**Comment by barotto** [comment]
_From VOGONS thread:_
ARPL won't write to memory unless it has to alter the value. If the page were write-protected, it would be a test against always-write (cmpxchg does the same).

**Comment by barotto** [comment]
I need help with the overflow flag of BCD instructions. There's no consensus on its value and Intel's documents don't help. This is the current situation:
```
op  | DOSBox    | Bochs | Intel  | hugi.scene.org  
----|-----------|-------|--------|------------  
AAA | defined   | false | undef. | unchanged  
AAS | defined   | false | undef. | unchanged  
AAM | false     | false | undef. | false  
AAD | false     | false | undef. | result  
DAA | unchanged | false | undef. | ?  
DAS | result    | false | undef. | ?  
```
Bochs' DAA, DAS are validated against Intel Pentium family hardware (or so they say)
Bochs' AAA, AAS, AAD, AAM are validated against Intel P6 family hardware (or so they say)
hugi.scene.org = http://www.hugi.scene.org/online/coding/hugi%2017%20-%20coaax.htm

Does its value change with the CPU family?

**Comment by peterferrie** [comment]
Yes, BCD behaviour changes according to the family, which is why I suggested pre-Pentium II as the base for testing (note that ARPL and CMPXCHG behaviour does not change).

AAA, AAS, DAA, DAS: overflow flag is set as expected for pre-Pentium II, untouched for Pentium II to pre-Pentium 4, always cleared for Pentium 4 and later.
AAM: unclear (possibly matching MUL flags, which I'm not allowed to describe)
AAD: as for ADD instruction.
