### ISSUE TITLE
arith-logic_d.asm

### ISSUE THREAD

**Issue by fysnet** [barotto/test386.asm#11]
Hi,

I was looking over your code and I believe I found two issues.  However, please note that I am not an expert, so I may be wrong here.

I believe starting with line 423 in arith-logic_d.asm, you copy and pasted from line 397, changed the "ROL" to "RCR", but forgot to change the actual instruction as well.  Therefore, your test still test for ROL instead of RCR.  Is this the case?

Second, at line 84, you define the defOpSh macro, but place a 'STC' instruction at line 96.  In my opinion, this implies that the processor will set the carry flag before it executes the rotation instruction.  What was your intention with the 'STC' instruction here?  Was this to check to make sure the carry flag was set correctly after the instruction?  Most likely.  Anyway, just asking.

Thank you,
Ben

**Comment by barotto** [comment]
Hi, first of all thanks for the bug report. At a first glance it seems like you're onto something. Unfortunately I'm a bit rusty on the matter so I need to get up to speed first. I'll get back to you as soon as I'll get my head around it.

**Comment by superfury** [comment]
> Hi,
> 
> I was looking over your code and I believe I found two issues. However, please note that I am not an expert, so I may be wrong here.
> 
> I believe starting with line 423 in arith-logic_d.asm, you copy and pasted from line 397, changed the "ROL" to "RCR", but forgot to change the actual instruction as well. Therefore, your test still test for ROL instead of RCR. Is this the case?
> 
> Second, at line 84, you define the defOpSh macro, but place a 'STC' instruction at line 96. In my opinion, this implies that the processor will set the carry flag before it executes the rotation instruction. What was your intention with the 'STC' instruction here? Was this to check to make sure the carry flag was set correctly after the instruction? Most likely. Anyway, just asking.
> 
> Thank you,
> Ben

I can confirm the first case to be indeed as you've mentioned. It's indeed executing the wrong instruction. It should be ",rcr," instead of ",rol,". That's from row 423-431.

About the second case: it's just to make sure that the operation has a defined input on the carry flag. It shifts/rotates from the carry into the parameter and from the parameter into the carry(rcl/rcr), while shl/shr/rol/ror don't shift from the carry flag. Refer to the intel processor documentation on those operations of the shift/rotate instructions.

**Comment by barotto** [comment]
I can confirm both of superfury's assessments.
I fell victim to the copypaste bug.
The carry flag is set to test if your cpu is correctly using it for rcr/rcl and not using it for normal shifts.

**Comment by fysnet** [comment]
I was pretty sure about the first case--that it was just a copy/paste issue.

The second case, I understand why you do it, though I guess my concern was that if I clear the carry before hand, before the test is ran for that particular instruction, the 'STC' voids me clearing it.  Nothing big.  Just was wondering why you chose to set the carry first.

For example, did the particular instruction *preserve* the carry?  If you set the carry, there is no way to know if the carry was preserved if the instruction was not to modify the carry flag.

For example, if the rotate instruction doesn't actually do a rotation, the carry is not to be touched.  By setting the carry and then doing a byte rotation with a count of 8, you can't tell if the carry was preserved from the last instruction to the next.

However, that being said, I understand why you would set it first, for all other types of instructions.  To have the carry at a known state beforehand.

Anyway, my main reason for the post was to inform you of the first issue noted.

Thanks and I enjoyed the read.
Ben

**Comment by barotto** [comment]
> The second case, I understand why you do it, though I guess my concern was that if I clear the carry before hand, before the test is ran for that particular instruction, the 'STC' voids me clearing it. Nothing big. Just was wondering why you chose to set the carry first.
> 
> For example, did the particular instruction _preserve_ the carry? If you set the carry, there is no way to know if the carry was preserved if the instruction was not to modify the carry flag.

You're correct, the CF is not fully tested, it can be wrongly set and you won't notice.

I guess the shift/rotate tests should be run twice, one with CF set and one with it cleared.

Although please consider that this is not the only case where an instruction is not tested for every possible input. In general if I say an instruction is tested, it's only for a limited set of input conditions. And if an instruction is officialy _not_ tested, nonetheless it may be used and "unofficially" tested in the sense that if it doesn't work the entire program would misbehave/crash.

Thanks again for the bug report.
