### ISSUE TITLE
8086 Version Help

### ISSUE THREAD

**Issue by davecom** [barotto/test386.asm#12]
Hi @barotto,
Thanks for creating this. It was suggested to me by some other folks developing emulators:
https://www.vogons.org/viewtopic.php?f=9&t=73677

My emulator only implements 8086 instructions and I was hoping you could point me in the right direction around some modifications I would need to make to strip out 186+ instructions from the project and get it to run as a BIOS on a PC 5150 or XT class emulator.

If I could help add a configuration option for 8086 mode that would be cool too.
Thanks in advance for any pointers.

**Comment by barotto** [comment]
Hi,  
I hope you're well versed in NASM Assembly because I suspect the amount of modifications would be substantial...  
Although support for more x86 CPUs has always been a goal for the project.  
Let me study the problem a bit, I'll get back to you once I've got a clearer picture.

**Comment by barotto** [comment]
The biggest problem for a 8086 port is that the **whole codebase** is written with the assumption that the CPU has 32bit registers.  

So support procedures, like for example those in print_p.asm, have to be rewritten for 16bit.  

Test procedures for 16bit instructions must be checked (and possibly rewriten) to make sure they don't use 32bit registers.  
For example the macro testMovSegR_real (in mov_m.asm) is used to test both 16bit and 32bit mov functionality.

As I see it it's better to create a test8086.asm project specific for the 8086.  
Maybe a bunch of tests can be ported directly from this project, but for the most part it would be a complete rewrite.

**Comment by davecom** [comment]
Thanks, @barotto. I appreciate you looking into it. It sounds like we will have to look into a different direction.
