### ISSUE TITLE
Implement Bochs' 0xE9 debugging port

### ISSUE THREAD

**Issue by barotto** [barotto/test386.asm#2]
https://bitbucket.org/superfury/unipcemu/wiki/Debugging

**Comment by superfury** [comment]
I've written a bit of assembly that can be inserted at the logging printing support in print_p.asm.
[test386-portE9hack.zip](https://github.com/barotto/test386.asm/files/1424217/test386-portE9hack.zip)

It works by simply detecting the port by probing it's value, then using it if it's detected.

**Comment by barotto** [comment]
I've decided to skip the autodetection because it would be called for every printed char, which would require too many cycles. A custom value in the config section will do.
