### ISSUE TITLE
Assembling error, symbol GP_HANDLER_SIG undefined

### ISSUE THREAD

**Issue by barotto** [barotto/test386.asm#8]
nasm -i./src/ -f bin src/test386.asm -w-all -l test386.lst -o test386.bin src/test386.asm:820:error: symbol GP_HANDLER_SIG' undefined
make: *** [test386] Error 1

**Interim solution:** turn on the Bochs support (BOCHS equ becoming 1) in _src/configuration.asm_

**Comment by superfury** [comment]
I've just pulled the latest commit, but that gets me the following compiler error:
```
nasm -i./src/ -f bin src/test386.asm -w-all -l test386.lst -o test386.bin
src/test386.asm:405: fatal: unable to open include file `protected_ring3_m.asm'
make: *** [test386] Error 1
```

**Comment by barotto** [comment]
Thanks, fixed.
I really need to stop being lazy and start using git branch...
